### ISSUE TITLE
[bug] 10px solid orange border added to unsplash body element 

### ISSUE THREAD

**Issue by navidmafi** [morceaudebois/unsplash-minus#1]
# Expected Behavior
Not having a 10px solid border on body.

# Current behavior  
![image](https://user-images.githubusercontent.com/46371349/210526669-ea728d1c-42db-4256-b19f-d46aaedeb7c4.png)
 
# Environment

Firefox 108.0.1

**Comment by morceaudebois** [comment]
Oops 😅 Welp, here's what happens when I try to do things too quickly, sorry about that! Will fix asap. Thanks a lot for the report :)

**Comment by morceaudebois** [comment]
Just posted the update on Firefox, you should get it soon once it's approved 😊

If I may ask, how did you find the addon? I just posted it and haven't even talked about it anywhere yet!

**Comment by navidmafi** [comment]
nice! will update soon.

I went to unsplash to find a new wallpaper and all of the Unsplash+ stuff were frustrating 

I just googled and found this extension 

![image](https://user-images.githubusercontent.com/46371349/210644683-a4eaeb7f-9fbe-47c8-be86-9f411c3837c7.png)
