### ISSUE TITLE
The extension is broken

### ISSUE THREAD

**Issue by guoyunhe** [morceaudebois/unsplash-minus#4]
Unsplash has changed its css class. So the extension is broken and I can still see those "Unsplash+" shit.

I have a solution with JS (I use it in TamperMonkey):

```js
(function() {
    'use strict';
    setInterval(() => {
        const figures = document.getElementsByTagName('figure');

        for (const figure of figures) {
            if (figure.textContent?.includes?.('Unsplash+')) {
                figure.remove();
            }
        }
    }, 1000);
})();
```

**Comment by morceaudebois** [comment]
Thanks a lot for bringing it to my attention! Fixed it in [my latest commit](https://github.com/morceaudebois/minus-for-unsplash/commit/f4370065af49e19b49d3d3f06f710ae1af3ddf8d).

I just pushed the update to Chrome and Firefox, it should be available in a few hours/days.
