### ISSUE TITLE
Remove collections curated by Unsplash+ 

### ISSUE THREAD

**Issue by victrme** [morceaudebois/unsplash-minus#5]
Hello 👋

When going through collections on https://unsplash.com/collections, we can see + collections that are not actually usable.  
See example:

<img width="868" alt="Capture d’écran 2024-04-11 à 15 24 04-min" src="https://github.com/morceaudebois/minus-for-unsplash/assets/34415964/11cd2500-9399-499a-85a5-31b0c36027e6">

**Comment by morceaudebois** [comment]
Now hiding collections in 1.4! Thank you 👀
